<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\Users\Chase\Documents\repo\Tempo_Threlte\static\models\boat.glb --root /models/ --printwidth 120 --precision 2
Author: Opus Poly (https://sketchfab.com/OpusPoly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gislinge-viking-boat-01098ad7973647a9b558f41d2ebc5193
Title: Gislinge Viking Boat
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/boat.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
  <T.Group scale={0.01}>
    <T.Mesh
      geometry={gltf.nodes.Rigging_Pin_Ship_Oak_Aged_0.geometry}
      material={gltf.materials.Ship_Oak_Aged}
      position={[-73.65, 62.37, 83.81]}
    />
    <T.Mesh
      geometry={gltf.nodes.Rigging_Pin001_Ship_Oak_Aged_0.geometry}
      material={gltf.materials.Ship_Oak_Aged}
      position={[72.43, 62.37, -151.98]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Rigging_Pin002_Ship_Oak_Aged_0.geometry}
      material={gltf.materials.Ship_Oak_Aged}
      position={[-72.66, 62.37, -151.98]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sail_Full_Sail_Full_0.geometry}
      material={gltf.materials.Sail_Full}
      position={[4.14, 420.92, 12.83]}
      rotation={[0, Math.PI / 6, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sail_Ropes_Ship_Oak_Aged_0.geometry}
      material={gltf.materials.Ship_Oak_Aged}
      position={[4.14, 420.92, 12.83]}
      rotation={[0, Math.PI / 6, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Yard_Ship_Oak_Aged_0.geometry}
      material={gltf.materials.Ship_Oak_Aged}
      position={[0, 425, 6.36]}
      rotation={[0, Math.PI / 6, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Yard_Rope_Raised_Ship_Oak_Aged_0.geometry}
      material={gltf.materials.Ship_Oak_Aged}
      position={[6.19, 95.83, 6.09]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mast_Ship_Oak_Aged_0.geometry}
      material={gltf.materials.Ship_Oak_Aged}
      position={[0, 18.51, 6.36]}
      rotation={[0, 1.48, Math.PI / 2]}
    />
    <T.Mesh geometry={gltf.nodes.Shrouds_Ship_Oak_Aged_0.geometry} material={gltf.materials.Ship_Oak_Aged} />
    <T.Mesh
      geometry={gltf.nodes.Stay_Ship_Oak_Aged_0.geometry}
      material={gltf.materials.Ship_Oak_Aged}
      position={[0, 92.01, 334.65]}
      rotation={[-0.73, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Yard_Rope_Ship_Oak_Aged_0.geometry}
      material={gltf.materials.Ship_Oak_Aged}
      position={[-6.63, 38.04, -73.1]}
    />
    <T.Mesh geometry={gltf.nodes.Keel_Ship_Oak_Aged_0.geometry} material={gltf.materials.Ship_Oak_Aged} />
    <T.Mesh geometry={gltf.nodes.Stems_Ship_Oak_Aged_0.geometry} material={gltf.materials.Ship_Oak_Aged} />
    <T.Mesh geometry={gltf.nodes.Planking_Ship_Oak_Aged_0.geometry} material={gltf.materials.Ship_Oak_Aged} />
    <T.Mesh geometry={gltf.nodes.Frames_Ship_Oak_Aged_0.geometry} material={gltf.materials.Ship_Oak_Aged} />
    <T.Mesh geometry={gltf.nodes.Stanchions_Ship_Oak_Aged_0.geometry} material={gltf.materials.Ship_Oak_Aged} />
    <T.Mesh geometry={gltf.nodes.Rudder_Frame_Ship_Oak_Aged_0.geometry} material={gltf.materials.Ship_Oak_Aged} />
    <T.Mesh geometry={gltf.nodes.Stringer_Ship_Oak_Aged_0.geometry} material={gltf.materials.Ship_Oak_Aged} />
    <T.Mesh geometry={gltf.nodes.Thole_Straps_Ship_Oak_Aged_0.geometry} material={gltf.materials.Ship_Oak_Aged} />
    <T.Mesh
      geometry={gltf.nodes.Rudder_Ship_Oak_Aged_0.geometry}
      material={gltf.materials.Ship_Oak_Aged}
      position={[-30.28, 68.37, -325.95]}
      rotation={[0.37, 0.08, 0.26]}
    />
    <T.Mesh
      geometry={gltf.nodes.Tiller_Ship_Oak_Aged_0.geometry}
      material={gltf.materials.Ship_Oak_Aged}
      position={[-2.41, 105.15, -311.13]}
      rotation={[0.28, 0, 0]}
    />
  </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
